CREATE DATABASE PremierLeagueAnalysis_raw;
GO

USE PremierLeagueAnalysis_raw;
GO


CREATE TABLE BettingOdds (
    [Date] DATE,
    [Time] TIME,
    HomeTeam VARCHAR(100),
    AwayTeam VARCHAR(100),
    FTHG INT,
    FTAG INT,
    FTR VARCHAR(100),
    HTHG INT,
    HTAG INT,
    HTR VARCHAR(100),
    Referee VARCHAR(100),
    HS INT,
    [AS] INT,
    HST INT,
    AST INT,
    HF INT,
    AF INT,
    HC INT,
    AC INT,
    HY INT,
    AY INT,
    HR INT,
    AR INT,
    B365H FLOAT,
    B365D FLOAT,
    B365A FLOAT,
    BWH FLOAT,
    BWD FLOAT,
    BWA FLOAT,
    IWH FLOAT,
    IWD FLOAT,
    IWA FLOAT,
    PSH FLOAT,
    PSD FLOAT,
    PSA FLOAT,
    WHH FLOAT,
    WHD FLOAT,
    WHA FLOAT,
    VCH FLOAT,
    VCD FLOAT,
    VCA FLOAT,
    MaxH FLOAT,
    MaxD FLOAT,
    MaxA FLOAT,
    AvgH FLOAT,
    AvgD FLOAT,
    AvgA FLOAT,
    B365_Over25 FLOAT,
    B365_Under25 FLOAT,
    P_Over25 FLOAT,
    P_Under25 FLOAT,
    Max_Over25 FLOAT,
    Max_Under25 FLOAT,
    Avg_Over25 FLOAT,
    Avg_Under25 FLOAT,
    AHh FLOAT,
    B365AHH FLOAT,
    B365AHA FLOAT,
    PAHH FLOAT,
    PAHA FLOAT,
    MaxAHH FLOAT,
    MaxAHA FLOAT,
    AvgAHH FLOAT,
    AvgAHA FLOAT,
    B365CH FLOAT,
    B365CD FLOAT,
    B365CA FLOAT,
    BWCH FLOAT,
    BWCD FLOAT,
    BWCA FLOAT,
    IWCH FLOAT,
    IWCD FLOAT,
    IWCA FLOAT,
    PSCH FLOAT,
    PSCD FLOAT,
    PSCA FLOAT,
    WHCH FLOAT,
    WHCD FLOAT,
    WHCA FLOAT,
    VCCH FLOAT,
    VCCD FLOAT,
    VCCA FLOAT,
    MaxCH FLOAT,
    MaxCD FLOAT,
    MaxCA FLOAT,
    AvgCH FLOAT,
    AvgCD FLOAT,
    AvgCA FLOAT,
    B365C_Over25 FLOAT,
    B365C_Under25 FLOAT,
    PC_Over25 FLOAT,
    PC_Under25 FLOAT,
    MaxC_Over25 FLOAT,
    MaxC_Under25 FLOAT,
    AvgC_Over25 FLOAT,
    AvgC_Under25 FLOAT,
    AHCh FLOAT,
    B365CAHH FLOAT,
    B365CAHA FLOAT,
    PCAHH FLOAT,
    PCAHA FLOAT,
    MaxCAHH FLOAT,
    MaxCAHA FLOAT,
    AvgCAHH FLOAT,
    AvgCAHA FLOAT
);


CREATE TABLE FantasyFixtures(
	[Date] Date,
	HomeTeamName VARCHAR(50),
	HomeTeamShortName	VARCHAR(3),
	AwayTeamName	VARCHAR(50),
	AwayTeamShortName	VARCHAR(3),
	HomeTeamDifficulty	INT,
	AwayTeamDifficulty	INT
);



CREATE TABLE Matches (
    Wk INT,
    Day VARCHAR(3),
    [Date] DATE,
    [Time] VARCHAR(50),
    Home VARCHAR(100),
    HomeXG DECIMAL(4,1),
    AwayXG DECIMAL(4,1),
    Away VARCHAR(100),
    Attendance INT,
    Venue VARCHAR(100),
    Referee VARCHAR(100),
	HomeScore INT,
	AwayScore INT
)